name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npx --package=renovate --call='RENOVATE_CONFIG_FILE=default.json renovate-config-validator' --yes

      - run: npx --package=renovate --call='RENOVATE_CONFIG_FILE=group:allNonMajorDependenciesExceptNodeJs.json renovate-config-validator' --yes

      - run: npx --package=renovate --call='RENOVATE_CONFIG_FILE=group:allNonMajorDevDependenciesExceptNodeJs.json renovate-config-validator' --yes
